In [5]:
import test.test_pathes as pt
import numpy as np
import pandas as pd
import os

In [6]:
all_result_d10 = np.empty([1, 3])
all_result_d30 = np.empty([1, 3])
all_result_d50 = np.empty([1, 3])

for i in range(1, 52):
    D10_csv = os.path.join(pt.path_D10_csv, str(i) + '.csv')
    df = pd.read_csv(D10_csv)
    df = df[['DESA', 'AGDE', 'GSK']].values
    all_result_d10 = np.concatenate((all_result_d10, df), axis=0)

    D30_csv = os.path.join(pt.path_D30_csv, str(i) + '.csv')
    df = pd.read_csv(D30_csv)
    df = df[['DESA', 'AGDE', 'GSK']].values
    all_result_d30 = np.concatenate((all_result_d30, df), axis=0)

    D50_csv = os.path.join(pt.path_D50_csv, str(i) + '.csv')
    df = pd.read_csv(D50_csv)
    df = df[['DESA', 'AGDE', 'GSK']].values
    all_result_d50 = np.concatenate((all_result_d50, df), axis=0)

all_result_d10 = np.delete(all_result_d10, 0, axis=0)
all_result_d30 = np.delete(all_result_d30, 0, axis=0)
all_result_d50 = np.delete(all_result_d50, 0, axis=0)

In [7]:
all_result_d50

array([[1.09315953e+12, 1.58359670e+12, 2.66066609e+12],
       [1.12473826e+79, 2.77725585e+88, 8.36199412e+94],
       [2.49761463e+05, 4.89740093e+05, 1.96901342e+12],
       ...,
       [6.82631786e+03, 9.21482399e+03, 1.04629947e+04],
       [1.19801503e+04, 2.14879945e+04, 3.55085033e+04],
       [7.86689875e+10, 1.18684619e+11, 1.64637659e+11]])

In [11]:
all_result_d10[:, 0]

array([1.89102974e+11, 2.53238825e+11, 1.60090081e+04, ...,
       3.52937805e+03, 3.86000214e+03, 1.06758795e+08])

In [19]:
desa_agde_1 = np.append(all_result_d10[:, 0], all_result_d30[:, 0], axis=0)
desa_agde_1 = np.append(desa_agde_1, all_result_d50[:, 0], axis=0)
desa_agde_1

array([1.89102974e+11, 2.53238825e+11, 1.60090081e+04, ...,
       6.82631786e+03, 1.19801503e+04, 7.86689875e+10])

In [20]:
desa_agde_2 = np.append(all_result_d10[:, 1], all_result_d30[:, 1], axis=0)
desa_agde_2 = np.append(desa_agde_2, all_result_d50[:, 1], axis=0)
desa_agde_2

array([2.44450107e+11, 4.87052271e+12, 2.49005433e+04, ...,
       9.21482399e+03, 2.14879945e+04, 1.18684619e+11])

In [21]:
desa_gsk_3 = np.append(all_result_d10[:, 2], all_result_d30[:, 2], axis=0)
desa_gsk_3 = np.append(desa_gsk_3, all_result_d50[:, 2], axis=0)
desa_gsk_3


array([2.50741725e+11, 8.51141699e+18, 3.94590327e+04, ...,
       1.04629947e+04, 3.55085033e+04, 1.64637659e+11])

In [45]:
desa_agde_R_plus = np.sum(desa_agde_1 <= desa_agde_2)
desa_agde_R_minus = np.sum(desa_agde_1 > desa_agde_2)
desa_agde_R_plus

3879

In [47]:
desa_gsk_R_plus = np.sum(desa_agde_1 <= desa_gsk_3)
desa_gsk_R_minus = np.sum(desa_agde_1 > desa_gsk_3)
desa_gsk_R_minus

17

In [71]:
import scipy.stats as ss

desa_agde_wilcoxon_static, desa_agde_wilcoxon_p = ss.wilcoxon(desa_agde_1, desa_agde_2, alternative='less')
format(desa_agde_wilcoxon_p, '.80f')

'0.00000000000000000000000000000000000000000000000000000000000000000000000000000000'

In [44]:
desa_gsk_wilcoxon_static, desa_gsk_wilcoxon_p = ss.wilcoxon(desa_agde_1, desa_gsk_3, alternative='less')
desa_gsk_wilcoxon_p

0.0

In [56]:
friedman_static, friedman_p = ss.friedmanchisquare(desa_agde_1, desa_agde_2, desa_gsk_3)
format(friedman_p, '.80f')

'0.00000000000000000000000000000000000000000000000000000000000000000000000000000000'

In [65]:
rank_array = ss.rankdata(np.append(desa_agde_1, np.append(desa_agde_2, desa_gsk_3)))
rank_array = rank_array.T
rank_array

array([10939. , 11157. ,  6470. , ...,  5620.5,  7386. , 10857.5])

In [66]:
desa_rank_mean = rank_array[0: 4130].mean()
agde_rank_mean = rank_array[4131: 8261].mean()
gsk_rank_mean = rank_array[8262: 12392].mean()

In [69]:
agde_rank_mean

6178.95774818402

In [77]:
df_R = pd.DataFrame([[desa_agde_R_plus, desa_agde_R_minus],
                     [desa_gsk_R_plus, desa_gsk_R_minus]], columns=['R+', 'R-'], index=['DESA vs AGDE', 'DESA vs GSK'])
df_R

R+   R-
DESA vs AGDE  3879  252
DESA vs GSK   4114   17

In [102]:
df_rank_mean = pd.DataFrame(np.array([desa_rank_mean, agde_rank_mean, gsk_rank_mean]).reshape(1, 3), columns=['DESA', 'AGDE', 'GSK'], index=['mean rank'])
df_rank_mean

DESA         AGDE         GSK
mean rank  5726.41816  6178.957748  6682.37724

In [103]:
df_R.to_csv(r'D:\profile\codes\python_projects\ocp\test\output\wilcoxon\wilcoxon_output\wilcoxon.csv')
df_rank_mean.to_csv(r'D:\profile\codes\python_projects\ocp\test\output\wilcoxon\wilcoxon_output\friedman_rank_mean.csv')

In [108]:
all_result = np.append(all_result_d10, np.append(all_result_d30, all_result_d50, axis=0), axis=0)
df_all = pd.DataFrame(all_result, columns=['DESA', 'AGDE', 'GSK'])
df_all

DESA          AGDE           GSK
0     1.891030e+11  2.444501e+11  2.507417e+11
1     2.532388e+11  4.870523e+12  8.511417e+18
2     1.600901e+04  2.490054e+04  3.945903e+04
3     2.538022e+03  3.928372e+03  4.341379e+03
4     6.275611e+02  6.677219e+02  7.238103e+02
...            ...           ...           ...
4126  1.376219e+04  3.963525e+04  6.050099e+04
4127  1.842957e+04  2.532642e+04  4.402048e+04
4128  6.826318e+03  9.214824e+03  1.046299e+04
4129  1.198015e+04  2.148799e+04  3.550850e+04
4130  7.866899e+10  1.186846e+11  1.646377e+11

[4131 rows x 3 columns]

In [112]:
df_all.to_csv('D:\profile\codes\python_projects\ocp\\test\output\wilcoxon\wilcoxon_output\\all_result.csv')